name: xhistogram_doc_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - xarray
  - netcdf4
  - numpy>=1.16
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - jupyter_client
  - ipykernel
  - pandoc
  - pip
  - doc8
  - pip:
    - nbsphinx
    - sphinx_rtd_theme
